spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc://localhost:3306/study_room_booking?useUnicode=true&characterEncoding=utf8&useSSL=true&serverTimezone=Asia/Shanghai
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}

jwt:
  secret: ${JWT_SECRET}
  expire: 86400000
  header: Authorization
  prefix: Bearer

mybatis-plus:
  configuration:
    log-impl: org.apache.ibatis.logging.nologging.NoLoggingImpl
